import * as fa from "react-icons/fa";
import Cookies from "js-cookie";

const Items = [

    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "HEAD-AREA",
        roles_HEADSTORE: "HEAD-STORE",
        roles_CASHIER: "CASHIER",
        roles_HEADWAREHOUSE: "-",
        title: "Dashboard",
        href: "/",
        text: "Dashboard",
        icon_item: "fi fi-rr-layout-fluid",
    },
    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "HEAD-AREA",
        title: "Cashier",
        href: "cashier",
        text: "Cashier",
        icon_item: "fi fi-rr-bags-shopping",
        path: "cashier",
        children: [
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADWAREHOUSE: "-",
                roles_CHANNEL: "asdasd",
                title: "Add Sales Online",
                href: "/cashier/add_order",
                icon_item: "fi fi-rr-database",
                text: "Add Sales Online",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                title: "Add Sales Offline",
                href: "/cashier/add_order_reseller",
                icon_item: "fi fi-br-list",
                text: "Add Sales Offline",
            },
        ],
    },
    {
        roles_CHANNEL: "SHOPEE" || "TOKOPEDIA" || "BLIBLI" || "LAZADA",
        title: "Cashier",
        href: "cashier",
        text: "Cashier",
        icon_item: "fi fi-rr-bags-shopping",
        path: "cashier",
        children: [
            {
                roles_HEADSTORE: "HEAD-STORE",
                roles_CASHIER: "CASHIER",
                roles_HEADWAREHOUSE: "-",
                roles_CHANNEL: "asdasd",
                title: "Add Sales Online",
                href: "/cashier/add_order",
                icon_item: "fi fi-rr-database",
                text: "Add Sales Online",
            },
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "HEAD-AREA",
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "CASHIER",
            //     roles_HEADWAREHOUSE: "-",
            //     title: "Add Sales Offline",
            //     href: "/cashier/add_order_reseller",
            //     icon_item: "fi fi-br-list",
            //     text: "Add Sales Offline",
            // },
        ],
    },
    {
        roles_CHANNEL: "OFFLINE STORE",
        title: "Cashier",
        href: "cashier",
        text: "Cashier",
        icon_item: "fi fi-rr-bags-shopping",
        path: "cashier",
        children: [
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "HEAD-AREA",
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "CASHIER",
            //     roles_CHANNEL: "asdasd",
            //     title: "Add Sales Online",
            //     href: "/cashier/add_order",
            //     icon_item: "fi fi-rr-database",
            //     text: "Add Sales Online",
            // },
            {
                roles_HEADSTORE: "HEAD-STORE",
                roles_CASHIER: "CASHIER",
                title: "Add Sales Offline",
                href: "/cashier/add_order_reseller",
                icon_item: "fi fi-br-list",
                text: "Add Sales Offline",
            },
        ],
    },
    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "HEAD-AREA",
        title: "Sales Report",
        href: "#",
        text: "Sales Report",
        icon_item: "fi fi-rr-bags-shopping",
        path: "report",
        children: [
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                title: "Report Sales Online",
                href: "/report/shipping",
                icon_item: "fi fi-rs-truck-side",
                text: "Report Sales Online",
            },
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "HEAD-AREA",
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "CASHIER",
            //     roles_HEADWAREHOUSE: "-",
            //     title: "Report Sales Retail",
            //     href: "/order_reseller/shipping_retail",
            //     icon_item: "fi fi-br-home",
            //     text: "Report Sales Retail",
            // },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                title: "Report Sales Offline",
                href: "/report/shipping_reseller",
                icon_item: "fi fi-ss-money-bill-wave",
                text: "Report Sales Offline",
            },
        ],
    },
    {
        roles_CHANNEL: "SHOPEE" || "TOKOPEDIA",
        title: "Sales Report",
        href: "#",
        text: "Sales Report",
        icon_item: "fi fi-rr-bags-shopping",
        path: "report",
        children: [
            {
                roles_HEADSTORE: "HEAD-STORE",
                roles_CASHIER: "CASHIER",
                roles_HEADWAREHOUSE: "-",
                title: "Report Sales Online",
                href: "/report/shipping",
                icon_item: "fi fi-rs-truck-side",
                text: "Report Sales Online",
            },
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "HEAD-AREA",
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "CASHIER",
            //     roles_HEADWAREHOUSE: "-",
            //     title: "Report Sales Retail",
            //     href: "/order_reseller/shipping_retail",
            //     icon_item: "fi fi-br-home",
            //     text: "Report Sales Retail",
            // },
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "HEAD-AREA",
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "CASHIER",
            //     roles_HEADWAREHOUSE: "-",
            //     title: "Report Sales Offline",
            //     href: "/report/shipping_reseller",
            //     icon_item: "fi fi-ss-money-bill-wave",
            //     text: "Report Sales Offline",
            // },
        ],
    },
    {
        roles_CHANNEL: "OFFLINE STORE",
        title: "Sales Report",
        href: "#",
        text: "Sales Report",
        icon_item: "fi fi-rr-bags-shopping",
        path: "report",
        children: [
            // {
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "CASHIER",
            //     roles_HEADWAREHOUSE: "-",
            //     title: "Report Sales Online",
            //     href: "/report/shipping",
            //     icon_item: "fi fi-rs-truck-side",
            //     text: "Report Sales Online",
            // },
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "HEAD-AREA",
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "CASHIER",
            //     roles_HEADWAREHOUSE: "-",
            //     title: "Report Sales Retail",
            //     href: "/order_reseller/shipping_retail",
            //     icon_item: "fi fi-br-home",
            //     text: "Report Sales Retail",
            // },
            {
                roles_HEADSTORE: "HEAD-STORE",
                roles_CASHIER: "CASHIER",
                roles_HEADWAREHOUSE: "-",
                title: "Report Sales Offline",
                href: "/report/shipping_reseller",
                icon_item: "fi fi-ss-money-bill-wave",
                text: "Report Sales Offline",
            },
        ],
    },
    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "HEAD-AREA",
        roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
        title: "Products",
        href: "#",
        text: "Products",
        icon_item: "fi fi-rr-box",
        path: "products",
        children: [
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Product List",
                href: "/products/daftar_produk",
                icon_item: "fi fi-rr-box-alt",
                text: "Product List",
            },
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "HEAD-AREA",
            //     roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
            //     title: "Product Sort A - Z",
            //     href: "/products/sortby",
            //     icon_item: "fi fi-rr-box-alt",
            //     text: "Product Sort A - Z",
            // },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_CHANNEL: "OFFLINE STORE",
                title: "Display Store",
                href: "/products/display_produk",
                icon_item: "fi fi-rr-file-invoice",
                text: "Display Store",
            },
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "HEAD-AREA",
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "-",
            //     roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
            //     title: "Produk Kembali",
            //     href: "/products/product_return",
            //     icon_item: "fi fi-rr-inbox-in",
            //     text: "Produk Kembali",
            // },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Report Order",
                href: "/products/pagepo",
                icon_item: "fi fi-rr-file-invoice-dollar",
                text: "Report Order",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Report Transfer",
                href: "/products/pagetransfer",
                icon_item: "fi fi-rr-file-invoice-dollar",
                text: "Report Transfer",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Report Stock Opname",
                href: "/products/pageso",
                icon_item: "fi fi-rr-folder-times",
                text: "Report Stock Opname",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Report Defect",
                href: "/products/pagedefect",
                icon_item: "fi fi-rr-folder-times",
                text: "Report Defect",
            },
        ],
    },
    {
        roles_HEADSTORE: "HEAD-STORE",
        roles_CASHIER: "CASHIER",
        title: "Products",
        href: "#",
        text: "Products",
        icon_item: "fi fi-rr-box",
        path: "products",
        children: [
            {
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                roles_HEADSTORE: "HEAD-STORE",
                roles_CASHIER: "CASHIER",
                title: "Product List",
                href: "/products/daftar_produk",
                icon_item: "fi fi-rr-box-alt",
                text: "Product List",
            },
            // {
            //     roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "CASHIER",
            //     title: "Product Sort A - Z",
            //     href: "/products/sortby",
            //     icon_item: "fi fi-rr-box-alt",
            //     text: "Product Sort A - Z",
            // },
            {
                roles_CHANNEL: "OFFLINE STORE",
                title: "Display Store",
                href: "/products/display_produk",
                icon_item: "fi fi-rr-file-invoice",
                text: "Display Store",
            },
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "HEAD-AREA",
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "-",
            //     roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
            //     title: "Produk Kembali",
            //     href: "/products/product_return",
            //     icon_item: "fi fi-rr-inbox-in",
            //     text: "Produk Kembali",
            // },
            {
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Report Order",
                href: "/products/pagepo",
                icon_item: "fi fi-rr-file-invoice-dollar",
                text: "Report Order",
            },
            {
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Report Transfer",
                href: "/products/pagetransfer",
                icon_item: "fi fi-rr-file-invoice-dollar",
                text: "Report Transfer",
            },
            {
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Report Stock Opname",
                href: "/products/pageso",
                icon_item: "fi fi-rr-folder-times",
                text: "Report Stock Opname",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Report Defect",
                href: "/products/pagedefect",
                icon_item: "fi fi-rr-folder-times",
                text: "Report Defect",
            },
        ],
    },
    {
        roles_GUEST: "GUEST",
        title: "Products",
        href: "#",
        text: "Products",
        icon_item: "fi fi-rr-box",
        path: "products",
        children: [
            {
                roles_GUEST: "GUEST",
                title: "Product List",
                href: "/products/daftar_produk",
                icon_item: "fi fi-rr-box-alt",
                text: "Product List",
            },
        ],
    },
    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "HEAD-AREA",
        roles_HEADSTORE: "HEAD-STORE",
        roles_CASHIER: "CASHIER",
        title: "Reseller",
        href: "/datamaster/reseller",
        text: "Reseller",
        icon_item: "fi fi-rr-user",
    },
    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "HEAD-AREA",
        roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
        roles_HEADSTORE: "HEAD-STORE",
        roles_CASHIER: "CASHIER",
        title: "Barcode",
        href: "/products/barcode",
        icon_item: "fi fi-ss-barcode-read",
        text: "Print Barcode",
    },
    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "HEAD-AREA",
        roles_HEADSTORE: "HEAD-STORE",
        roles_CASHIER: "-",
        roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
        title: "History Product",
        href: "#",
        text: "History Product",
        icon_item: "fi fi-rr-time-past",
        path: "histories",
        children: [
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "HEAD-STORE",
                roles_CASHIER: "CASHIER",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Histories",
                href: "/histories/histories",
                icon_item: "fi fi-rr-notebook",
                text: "Histories",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "HEAD-STORE",
                roles_CASHIER: "CASHIER",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Mutasi Stock",
                href: "/histories/mutasi_stock",
                icon_item: "fi fi-rr-notebook",
                text: "Mutasi Stock",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "HEAD-STORE",
                roles_CASHIER: "CASHIER",
                roles_HEADWAREHOUSE: "-",
                title: "Delete Order",
                href: "/histories/histori_delete",
                icon_item: "fi fi-rr-trash",
                text: "Delete Order",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "HEAD-STORE",
                roles_CASHIER: "CASHIER",
                roles_HEADWAREHOUSE: "-",
                title: "Return Size",
                href: "/histories/histori_retur",
                icon_item: "fi fi-rr-shuffle",
                text: "Return Size",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "HEAD-STORE",
                roles_CASHIER: "CASHIER",
                roles_HEADWAREHOUSE: "-",
                title: "Refund",
                href: "/histories/histori_refund",
                icon_item: "fi fi-br-cross",
                text: "Refund",
            },
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "HEAD-AREA",
            //     roles_HEADSTORE: "HEAD-STORE",
            //     roles_CASHIER: "CASHIER",
            //     roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
            //     title: "Tukar Model",
            //     href: "/histories/histori_tukar_model",
            //     icon_item: "fi fi-rr-replace",
            //     text: "Tukar Model",
            // },
            // {
            //     "title": "Histori Retur",
            //     "href": "/histories/histori_retur",
            //     "icon_item": "fi fi-rr-recycle",
            //     "text": "Histori Retur"
            // }, {
            //     "title": "Histori Refund",
            //     "href": "/histories/histori_refund",
            //     "icon_item": "fi fi-rr-inbox-in",
            //     "text": "Histori Refund"
            // },
        ],
    },
    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "HEAD-AREA",
        roles_HEADSTORE: "-",
        roles_HEADWAREHOUSE: "-",
        title: "Data Master",
        href: "#",
        text: "Data Master",
        icon_item: "fi fi-rr-folder",
        path: "datamaster",
        children: [
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "-",
                roles_CASHIER: "-",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Area",
                href: "/datamaster/area",
                icon_item: "fi fi-rs-map-marker",
                text: "Area",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "-",
                roles_CASHIER: "-",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Warehouse",
                href: "/datamaster/warehouse",
                icon_item: "fi fi-rr-garage",
                text: "Warehouse",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "-",
                roles_CASHIER: "-",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Store",
                href: "/datamaster/store",
                icon_item: "fi fi-rr-shop",
                text: "Store",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "-",
                roles_CASHIER: "-",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Brand",
                href: "/datamaster/brand",
                icon_item: "fi fi-rr-tags",
                text: "Brand",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "-",
                roles_CASHIER: "-",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Category",
                href: "/datamaster/category",
                icon_item: "fi fi-rr-cube",
                text: "Category",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "HEAD-AREA",
                roles_HEADSTORE: "-",
                roles_CASHIER: "-",
                roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
                title: "Supplier",
                href: "/datamaster/supplier",
                icon_item: "fi fi-rr-package",
                text: "Supplier",
            },
            {
                roles_SUPERADMIN: "SUPER-ADMIN",
                roles_HEADAREA: "-",
                roles_HEADSTORE: "-",
                roles_CASHIER: "-",
                roles_HEADWAREHOUSE: "-",
                title: "Employee",
                href: "/datamaster/karyawan",
                icon_item: "fi fi-rr-user",
                text: "Employee",
            },
            // {
            //     roles_SUPERADMIN: "SUPER-ADMIN",
            //     roles_HEADAREA: "-",
            //     roles_HEADSTORE: "-",
            //     roles_CASHIER: "-",
            //     roles_HEADWAREHOUSE: "-",
            //     title: "Reseller",
            //     href: "/datamaster/reseller",
            //     icon_item: "fi fi-rr-user",
            //     text: "Reseller",
            // },
        ],
    },
    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "HEAD-AREA",
        roles_CHANNEL: "OFFLINE STORE",
        title: "Store Expense",
        href: "/expense",
        text: "Store Expense",
        icon_item: "fi fi-rr-label",
    },
    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "-",
        roles_HEADSTORE: "-",
        roles_CASHIER: "-",
        roles_HEADWAREHOUSE: "-",
        title: "Assets",
        href: "/assets",
        text: "Assets",
        icon_item: "fi fi-rs-sack-dollar",
    },
    {
        roles_SUPERADMIN: "SUPER-ADMIN",
        roles_HEADAREA: "HEAD-AREA",
        roles_HEADSTORE: "HEAD-STORE",
        roles_CASHIER: "CASHIER",
        roles_HEADWAREHOUSE: "HEAD-WAREHOUSE",
        title: "Settings",
        href: "/settings/setting",
        text: "Settings",
        icon_item: "fi fi-rr-settings",
    },
];

export default Items;
